#!/usr/bin/env python3
"""Generate DHUN Web's demo audio.

Why this exists
---------------
The web client ships with a "demo mode" so its player, queue, seek, shuffle
and Media Session code paths are exercisable with no bridge and no network.
That needs *something* to play. Rather than committing binaries to Git, the
tracks are synthesised here — stdlib only (``wave`` + ``math``), no deps — and
regenerated by the Pages workflow at build time.

Output: web/assets/demo/demo-{1,2,3}.wav  (16 kHz, 16-bit, mono)

Usage:
    python3 web/tools/make-demo-audio.py [--out web/assets/demo] [--seconds 24]
"""

from __future__ import annotations

import argparse
import math
import os
import struct
import sys
import wave

SAMPLE_RATE = 16000

# Chord progressions (root MIDI notes) give each demo track a different mood.
TRACKS = [
    {
        "file": "demo-1.wav",
        "name": "Signal Drift",
        # i - VI - III - VII in A minor, one bar each.
        "progression": [[57, 60, 64], [53, 57, 60], [48, 52, 55], [55, 59, 62]],
        "bpm": 92,
        "waveform": "triangle",
    },
    {
        "file": "demo-2.wav",
        "name": "Low Orbit",
        "progression": [[45, 52, 57], [43, 50, 55], [41, 48, 53], [46, 53, 58]],
        "bpm": 76,
        "waveform": "sine",
    },
    {
        "file": "demo-3.wav",
        "name": "Nightbus",
        "progression": [[50, 53, 57], [55, 59, 62], [48, 52, 55], [53, 57, 60]],
        "bpm": 104,
        "waveform": "triangle",
    },
]


def midi_to_hz(midi: float) -> float:
    return 440.0 * (2.0 ** ((midi - 69.0) / 12.0))


def waveform_value(phase: float, kind: str) -> float:
    """One sample of the oscillator, normalised to roughly [-1, 1]."""
    if kind == "sine":
        return math.sin(phase)
    # Triangle: cheap, harmonically warmer than a sine for the pad voices.
    return 2.0 / math.pi * math.asin(math.sin(phase))


def adsr(t: float, duration: float, attack: float = 0.08, release: float = 0.35) -> float:
    """Simple attack/sustain/release envelope. ``t`` is seconds into the note."""
    if t < 0 or t > duration:
        return 0.0
    if t < attack:
        return t / attack
    release_start = duration - release
    if t > release_start:
        remaining = (duration - t) / max(release, 1e-6)
        return max(0.0, remaining)
    return 1.0


def render_track(spec: dict, seconds: float) -> list[float]:
    """Mix a chord pad plus an eighth-note arpeggio over the progression."""
    total = int(SAMPLE_RATE * seconds)
    buffer = [0.0] * total

    beat = 60.0 / spec["bpm"]
    bar = beat * 4
    note_len = beat / 2  # eighth notes

    chord_index = 0
    position = 0.0
    while position < seconds:
        chord = spec["progression"][chord_index % len(spec["progression"])]

        # Pad: whole-bar chord, slightly detuned for width.
        for note in chord:
            add_voice(buffer, midi_to_hz(note), position, min(bar, seconds - position),
                      spec["waveform"], gain=0.10, detune=1.004)
            add_voice(buffer, midi_to_hz(note), position, min(bar, seconds - position),
                      spec["waveform"], gain=0.07)

        # Arpeggio: cycle the chord tones an octave up.
        step = 0
        arpeggio_pos = position
        while arpeggio_pos < min(position + bar, seconds):
            note = chord[step % len(chord)] + 12
            add_voice(buffer, midi_to_hz(note), arpeggio_pos, note_len * 0.9,
                      "sine", gain=0.13)
            arpeggio_pos += note_len
            step += 1

        position += bar
        chord_index += 1

    # Gentle feedback delay — a poor man's reverb, keeps it from sounding dead.
    delay_samples = int(SAMPLE_RATE * 0.28)
    for i in range(delay_samples, total):
        buffer[i] += buffer[i - delay_samples] * 0.28

    peak = max((abs(s) for s in buffer), default=1.0) or 1.0
    headroom = 0.89 / peak
    return [s * headroom for s in buffer]


def add_voice(buffer: list[float], freq: float, start: float, duration: float,
              kind: str, gain: float, detune: float = 1.0) -> None:
    """Add one enveloped oscillator voice into ``buffer`` (in place)."""
    total = len(buffer)
    first = int(start * SAMPLE_RATE)
    count = int(duration * SAMPLE_RATE)
    phase_step = 2.0 * math.pi * freq * detune / SAMPLE_RATE
    phase = 0.0
    for offset in range(count):
        index = first + offset
        if index >= total:
            break
        t = offset / SAMPLE_RATE
        envelope = adsr(t, duration)
        if envelope <= 0.0:
            phase += phase_step
            continue
        buffer[index] += waveform_value(phase, kind) * envelope * gain
        phase += phase_step


def write_wav(path: str, samples: list[float]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with wave.open(path, "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(SAMPLE_RATE)
        frames = bytearray()
        for sample in samples:
            clamped = max(-1.0, min(1.0, sample))
            frames += struct.pack("<h", int(clamped * 32767))
        out.writeframes(bytes(frames))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    default_out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                               "assets", "demo")
    parser.add_argument("--out", default=default_out, help="output directory")
    parser.add_argument("--seconds", type=float, default=24.0, help="track length")
    args = parser.parse_args(argv)

    for spec in TRACKS:
        path = os.path.join(args.out, spec["file"])
        samples = render_track(spec, args.seconds)
        write_wav(path, samples)
        print(f"wrote {path} ({os.path.getsize(path) / 1024:.0f} KiB) — {spec['name']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
